PREFIX ?= /usr/local
BINARY = apfel

.PHONY: build install uninstall clean version-bump buildinfo

buildinfo:
	@v=$$(grep 'let version = ' Sources/main.swift | head -1 | sed 's/.*"\(.*\)"/\1/'); \
	commit=$$(git rev-parse --short HEAD 2>/dev/null || echo "unknown"); \
	branch=$$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown"); \
	date=$$(date -u +"%Y-%m-%d %H:%M:%S UTC"); \
	swift_ver=$$(swift --version 2>/dev/null | head -1 | sed 's/.*version //' | sed 's/ .*//'); \
	os_ver=$$(sw_vers -productVersion 2>/dev/null || echo "unknown"); \
	echo '// Auto-generated by make — do not edit' > Sources/BuildInfo.swift; \
	echo '// Regenerated on every build' >> Sources/BuildInfo.swift; \
	echo '' >> Sources/BuildInfo.swift; \
	echo "let buildVersion = \"$$v\"" >> Sources/BuildInfo.swift; \
	echo "let buildCommit = \"$$commit\"" >> Sources/BuildInfo.swift; \
	echo "let buildBranch = \"$$branch\"" >> Sources/BuildInfo.swift; \
	echo "let buildDate = \"$$date\"" >> Sources/BuildInfo.swift; \
	echo "let buildSwiftVersion = \"$$swift_ver\"" >> Sources/BuildInfo.swift; \
	echo "let buildOS = \"macOS $$os_ver\"" >> Sources/BuildInfo.swift

build: buildinfo
	swift build -c release

install: build
	@pkill -f "apfel --serve" 2>/dev/null || true
	@pkill -f "apfel --gui" 2>/dev/null || true
	@sleep 1
	@if [ -w "$(PREFIX)/bin" ]; then \
		install .build/release/$(BINARY) $(PREFIX)/bin/$(BINARY); \
	else \
		sudo install .build/release/$(BINARY) $(PREFIX)/bin/$(BINARY); \
	fi
	@echo "✓ installed: $$($(PREFIX)/bin/$(BINARY) --version)"

uninstall:
	@if [ -w "$(PREFIX)/bin" ]; then \
		rm -f $(PREFIX)/bin/$(BINARY); \
	else \
		sudo rm -f $(PREFIX)/bin/$(BINARY); \
	fi

clean:
	swift package clean
	rm -f Sources/BuildInfo.swift

version-bump:
	@v=$$(grep 'let version = ' Sources/main.swift | head -1 | sed 's/.*"\(.*\)"/\1/'); \
	major=$$(echo $$v | cut -d. -f1); \
	minor=$$(echo $$v | cut -d. -f2); \
	patch=$$(echo $$v | cut -d. -f3); \
	new="$$major.$$minor.$$((patch+1))"; \
	sed -i '' "s/let version = \"$$v\"/let version = \"$$new\"/" Sources/main.swift; \
	echo "$$v → $$new"
