// Auto-generated by make — do not edit
let buildVersion = "0.6.34"
let buildCommit = "385ba14"
let buildBranch = "main"
let buildDate = "2026-04-04 07:34:14 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
