// Auto-generated by make — do not edit
let buildVersion = "1.10.0"
let buildCommit = "5f5114b"
let buildBranch = "main"
let buildDate = "2026-09-07 17:22:18 UTC"
let buildSwiftVersion = "6.3.3"
let buildOS = "macOS 26.5.2"
