// Auto-generated by make — do not edit
let buildVersion = "1.0.3"
let buildCommit = "e3d13e7"
let buildBranch = "main"
let buildDate = "2026-04-15 11:49:01 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
